RES = WIDTH, HEIGHT = 1200, 860
TILE = 30
cols, rows = WIDTH // TILE, HEIGHT // TILE
FINISH = cols*rows-1

MAX_POPULATION = 1
POPULATION_SIZE = 100
MAX_ITERATION = POPULATION_SIZE/TILE*100
P_CROSSOVER = 0.0
P_MUTATION = 0.0

SHOW_EVOLUTION = False
