RES = WIDTH, HEIGHT = 1200, 860
TILE = 40
cols, rows = WIDTH // TILE, HEIGHT // TILE
FINISH = cols*rows-1

MAX_POPULATION = 1
POPULATION_SIZE = 300
MAX_ITERATION = POPULATION_SIZE/TILE*80
P_CROSSOVER = 0.9
P_MUTATION = 0.3

SHOW_EVOLUTION = False

